version: '3'

networks:
  url-shortener:
    driver: bridge

services:
  db:
    container_name: url-shortener-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - db.env
    networks:
      - url-shortener
  api:
    container_name: url-shortener-api
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - api.env
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    networks:
      - url-shortener
